image: proboci/ubuntu-16.04-lamp:php7.2-nightly
steps:
  - name: Update composer
    command: '/usr/local/bin/composer self-update'
  - name: Require drush 8.1.15. (Required for Drupal 8.4.5+)
    command: 'cd /src && composer global require drush/drush:8.1.15'
  - name: Install composer packages with dependencies.
    command: 'composer install -d /src'
  - name: Install Drupal
    plugin: Drupal
    runInstall: true
    profileName: standard
    clearCaches: false
    subDirectory: web
